### ISSUE TITLE
yarn strapi-generate-types generate or yarn strapi-generate-type generate

### ISSUE THREAD

**Issue by mannp** [Stun3R/strapi-generate-types#6]
Hi there

Thanks for creating

Is there a typo when executing the command?

For me its yarn strapi-generate-type generate not yarn strapi-generate-type**s** generate

**Comment by Stun3R** [comment]
Hi @mannp 👋🏻,

You're right! It should be `yarn strapi-generate-types`

I'm going to fix it ;)
